project_id = "sbxltdbnqixucjoognfj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = false

[inbucket]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions]
enabled = true

[functions.admin-users]
verify_jwt = true

[functions.list-available-instances]
verify_jwt = true

[functions.get-instance-contacts]
verify_jwt = true

[functions.send-scheduled-messages]
verify_jwt = false

[functions.scan-duplicate-proposals]
verify_jwt = true

[functions.analyze-image]
verify_jwt = false